# Generated by Django 3.0 on 2020-05-21 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waev', '0005_auto_20200514_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiofile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
